import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"

interface POItem {
  id: string
  lineNumber: number
  itemName: string
  description?: string
  quantity: string
  unitPrice: string
  totalPrice: string
}

interface POData {
  po: {
    id: string
    poNumber: string
    requestId: string
    vendorId?: string
    status: string
    totalAmount: string
    currency: string
    expectedDelivery?: Date
    createdBy: string
    issuedAt?: Date
    createdAt: Date
  }
  items: POItem[]
  request?: {
    id: string
    number: string
    title: string
  }
  vendor?: {
    id: string
    vendorName: string
    email?: string
    company?: string
  }
}

export function generatePurchaseOrderPdf(data: POData): void {
  const { po, items, request, vendor } = data

  // Create PDF with A4 size
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setFont("helvetica", "bold")
  doc.text("ProcureAI", 20, yPosition)
  yPosition += 12

  // PO Title and Number
  doc.setFontSize(14)
  doc.text(`Purchase Order: ${po.poNumber}`, 20, yPosition)
  yPosition += 10

  // Issue Date and Status
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  const issueDate = po.issuedAt ? new Date(po.issuedAt).toLocaleDateString() : new Date(po.createdAt).toLocaleDateString()
  doc.text(`Issue Date: ${issueDate}`, 20, yPosition)
  yPosition += 6
  doc.text(`Status: ${po.status}`, 20, yPosition)
  yPosition += 12

  // Vendor Information
  if (vendor) {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(11)
    doc.text("Vendor Information", 20, yPosition)
    yPosition += 7

    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.text(`Name: ${vendor.vendorName}`, 20, yPosition)
    yPosition += 5
    if (vendor.email) {
      doc.text(`Email: ${vendor.email}`, 20, yPosition)
      yPosition += 5
    }
    if (vendor.company) {
      doc.text(`Company: ${vendor.company}`, 20, yPosition)
      yPosition += 5
    }
  }
  yPosition += 5

  // Request Details
  if (request) {
    doc.setFont("helvetica", "bold")
    doc.setFontSize(11)
    doc.text("Request Details", 20, yPosition)
    yPosition += 7

    doc.setFont("helvetica", "normal")
    doc.setFontSize(10)
    doc.text(`Request Number: ${request.number}`, 20, yPosition)
    yPosition += 5
    doc.text(`Title: ${request.title}`, 20, yPosition)
    yPosition += 10
  }

  // PO Details
  doc.setFont("helvetica", "bold")
  doc.setFontSize(11)
  doc.text("Purchase Order Details", 20, yPosition)
  yPosition += 10

  // Items Table
  const tableData = items.map((item) => [
    item.lineNumber.toString(),
    item.itemName,
    item.quantity,
    item.unitPrice,
    item.totalPrice,
  ])

  autoTable(doc, {
    head: [["Line", "Item", "Quantity", "Unit Price", "Total"]],
    body: tableData,
    startY: yPosition,
    margin: 20,
    styles: {
      fontSize: 9,
      cellPadding: 5,
    },
    headStyles: {
      fillColor: [41, 128, 185],
      textColor: 255,
      fontStyle: "bold",
    },
    alternateRowStyles: {
      fillColor: [240, 240, 240],
    },
  })

  yPosition = (doc as any).lastAutoTable.finalY + 15

  // Summary
  doc.setFont("helvetica", "bold")
  doc.setFontSize(10)
  doc.text(`Total Amount: ${po.currency} ${po.totalAmount}`, pageWidth - 80, yPosition)
  yPosition += 7

  if (po.expectedDelivery) {
    const deliveryDate = new Date(po.expectedDelivery).toLocaleDateString()
    doc.text(`Expected Delivery: ${deliveryDate}`, pageWidth - 80, yPosition)
    yPosition += 7
  }

  // Footer
  doc.setFont("helvetica", "normal")
  doc.setFontSize(8)
  doc.text("Generated by ProcureAI", 20, pageHeight - 15)

  // Download
  doc.save(`PO-${po.poNumber}.pdf`)
}
